question:
    pattern:  /
    defaults: { _controller: "TipddySurveyBundle:Question:index" }
    requirements: { survey: \d+ }

question_show:
    pattern:  /{id}/show
    defaults: { _controller: "TipddySurveyBundle:Question:show" }

question_new:
    pattern:  /new
    defaults: { _controller: "TipddySurveyBundle:Question:new" }

question_create:
    pattern:  /create
    defaults: { _controller: "TipddySurveyBundle:Question:create" }
    requirements: { _method: post }

question_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TipddySurveyBundle:Question:edit" }

question_update:
    pattern:  /{id}/update
    defaults: { _controller: "TipddySurveyBundle:Question:update" }
    requirements: { _method: post|put }

question_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TipddySurveyBundle:Question:delete" }
    requirements: { _method: post|delete }
